services:
  - type: web
    name: lms
    env: php
    plan: free
    region: oregon
    buildCommand: 'composer install && php artisan migrate'
    startCommand: 'php artisan serve --host 0.0.0.0 --port 10000'
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://lms.onrender.com
